### ISSUE TITLE
strange character in the generated code prevents copy of all code

### ISSUE THREAD

**Issue by lownotesb** [russellgoldenberg/responsive-table-generator#23]
This is a really cool tool that you have.  I'm having problems with copy and paste of the generated code.  I think I've identified an odd character in the code that causes my copy to stop at that character.  I do Select-All but when I paste it stops exactly where this weird character is in the table CSS.  So I'm assuming it's not coming from my table.

![responsive tables](https://cloud.githubusercontent.com/assets/8644980/12129550/99ba2fd4-b3c1-11e5-9f7c-d6384c2b8f2c.jpg)

**Comment by russellgoldenberg** [comment]
what browser are you using?

**Comment by lownotesb** [comment]
most current firefox, i can actually delete the character out of the text
box before copy and then it works as intended.

On Tue, Jan 5, 2016 at 3:44 PM, Russell Goldenberg <notifications@github.com

**Comment by lownotesb** [comment]
works fine on chrome, sorry should have checked that.  at least you know
about it.

**Comment by russellgoldenberg** [comment]
Thanks I see it as well in Firefox, will fix.

**Comment by rachelchartoff** [comment]
I am also experiencing issues with copy and paste in Firefox. Can you advise when this is fixed? Will try Chrome in the meantime. Thanks.
